steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/analog-context-413503/kevinleandertest/python-app:${COMMIT_SHA}', '.']

  # Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast2-docker.pkg.dev/analog-context-413503/kevinleandertest/python-app:${COMMIT_SHA}']

  # Deploy the Docker container to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'python-app'
      - '--image=northamerica-northeast2-docker.pkg.dev/analog-context-413503/kevinleandertest/python-app:${COMMIT_SHA}'
      - '--platform=managed'
      - '--region=us-central1'
      - '--port=3000'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--concurrency=80'
      - '--timeout=5s'
      - '--allow-unauthenticated'

  # Publish a message to Pub/Sub when the deployment is finished
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['pubsub', 'topics', 'publish', 'midterm', '--message', 'Successfully created.']

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

images:
  - northamerica-northeast2-docker.pkg.dev/analog-context-413503/kevinleandertest/python-app:${COMMIT_SHA}
